management:
  security:
    enabled: false
    
server:
  port: 8084
  
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka
      
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/rueggerllc
    username: chris
    password: dakota
    driverClassName: com.mysql.jdbc.Driver
    
  jpa:
    database-platform:  org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
        
logging:
  level:
    com.rueggerllc.bookcatalog: debug
  file: C:\logs\BookCatalogService-default.log
  
msg: Hello From The Book Service!